dist: bionic
sudo: false
language: python

addons:
  postgresql: "10"
  apt_packages:
    - enchant

matrix:
  fast_finish: true
  include:
    - python: 3.7
      name: "django-oscar-project-test-travis-ci" 
      env: TOXENV=py37-django30

branches:
  only:
  - master
  - /^releases.*$/

env:
  global:
    # These two environment variables could be set by Travis itself, or Travis
    # could configure itself in /etc/, ~/, or inside of the virtual
    # environments. In any case if these two values get configured then end
    # users only need to enable the pip cache and manually run pip wheel before
    # running pip install.
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels


before_cache:
  - rm -rf $HOME/.cache/pip/log


cache:
  directories:
    - $HOME/.cache/pip


install:
  - pip install tox codecov requests


script:
  - tox


after_success:
  - codecov
